<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="01-数据类型\" />
    <Folder Include="02-判断与运算符\" />
    <Folder Include="03-字符串\" />
    <Folder Include="04-循环\" />
    <Folder Include="05-数组\" />
    <Folder Include="06-集合\" />
    <Folder Include="07-结构体\" />
    <Folder Include="08-类\" />
    <Folder Include="09-接口\" />
    <Folder Include="10-预处理器指令\" />
    <Folder Include="11-using的用法\" />
    <Folder Include="12-正则表达式\" />
    <Folder Include="13-IO处理\" />
    <Folder Include="14-数据处理\" />
    <Folder Include="15-Linq表达式\" />
  </ItemGroup>
</Project>
